#pragma once
#include <algorithm>
#include <array>
#include <atomic>
#include <cassert>
#include <chrono>
#define _USE_MATH_DEFINES
#include <cmath>
#include <condition_variable>
#include <cstdint>
#include <cstring>
#include <cstdio> 
#include <ctime> 
#include <filesystem>
#include <fstream>
#include <functional>
#include <future>
#include <iostream>
#include <memory>
#include <mutex>
#include <span>
#include <sstream>
#include <stack>
#include <stacktrace>
#include <stdexcept>
#include <string>
#include <string_view>
#include <thread>
#include <tuple>
#include <unordered_map>
#include <unordered_set>
#include <utility>
#include <variant>
#include <vector>

using std::async;
using std::atomic;
using std::atomic_bool;
using std::array;
using std::clamp;
using std::chrono::duration;
using std::chrono::duration_cast;
using std::chrono::high_resolution_clock;
using std::chrono::microseconds;
using std::chrono::milliseconds;
using std::chrono::seconds;
using std::condition_variable;
using std::endl;
using std::future;
using std::get;
using std::get_if;
using std::holds_alternative;
using std::launch;
using std::lock_guard;
using std::make_shared;
using std::make_unique;
using std::max;
using std::min;
using std::mutex;
using std::pair;
using std::ostream;
using std::ostringstream;
using std::recursive_mutex;
using std::shared_ptr;
using std::span;
using std::string;
using std::stringstream;
using std::string_view;
using std::this_thread::sleep_for;
using std::thread;
using std::tuple;
using std::unique_ptr;
using std::unique_lock;
using std::unordered_map;
using std::variant;
using std::vector;
using std::weak_ptr;
using std::unordered_set;
