// compiler/Parser.cpp
// LALR(1) table-driven parser.
// Tables are in ParseTables.h (auto-generated by tools/lalr_gen.py).
// This file implements the shift/reduce engine and semantic actions.
//
#include "pch/pch.h"
#include "Parser.h"
#include "ParseTables.h"

#include <filesystem>
#include <fstream>
#include <iostream>
#include <vector>

namespace fs = std::filesystem;

namespace xmc {

using TT = Lexer::TokenType;
static constexpr int32_t ACCEPT_VAL = 0x7FFFFFFF;

// ─────────────────────────────────────────────────────────────────────────────
// ParseKindName
// ─────────────────────────────────────────────────────────────────────────────

const char* ParseKindName(ParseKind k) {
    switch (k) {
    case ParseKind::Unknown:      return "Unknown";
    case ParseKind::File:         return "File";
    case ParseKind::ExternDecl:   return "ExternDecl";
    case ParseKind::FuncDecl:     return "FuncDecl";
    case ParseKind::ParamList:    return "ParamList";
    case ParseKind::Param:        return "Param";
    case ParseKind::ReturnSpec:   return "ReturnSpec";
    case ParseKind::Type:         return "Type";
    case ParseKind::Block:        return "Block";
    case ParseKind::VarDecl:      return "VarDecl";
    case ParseKind::ExprStmt:     return "ExprStmt";
    case ParseKind::Return:       return "Return";
    case ParseKind::ArgList:      return "ArgList";
    case ParseKind::Assign:       return "Assign";
    case ParseKind::Call:         return "Call";
    case ParseKind::MemberAccess: return "MemberAccess";
    case ParseKind::Subscript:    return "Subscript";
    case ParseKind::AddressOf:    return "AddressOf";
    case ParseKind::Deref:        return "Deref";
    case ParseKind::Negate:       return "Negate";
    case ParseKind::UnaryPlus:    return "UnaryPlus";
    case ParseKind::Not:          return "Not";
    case ParseKind::BitNot:       return "BitNot";
    case ParseKind::BinOp:        return "BinOp";
    case ParseKind::Ident:        return "Ident";
    case ParseKind::IntLit:       return "IntLit";
    case ParseKind::FloatLit:     return "FloatLit";
    case ParseKind::StringLit:    return "StringLit";
    case ParseKind::CharLit:      return "CharLit";
    case ParseKind::BoolLit:      return "BoolLit";
    case ParseKind::NullLit:      return "NullLit";
    case ParseKind::Stub:         return "Stub";
    default:                      return "?";
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// Token → terminal index (jump table; no strings at runtime)
// ─────────────────────────────────────────────────────────────────────────────

static int TermIdx(TT tt) {
    switch (tt) {
    case TT::LIT_INTEGER:          return XMC_TERM_INTEGER_LITERAL;
    case TT::LIT_FLOAT:            return XMC_TERM_FLOAT_LITERAL;
    case TT::LIT_DECIMAL:          return XMC_TERM_DECIMAL_LITERAL;
    case TT::LIT_STRING:           return XMC_TERM_STRING_LITERAL;
    case TT::LIT_CHAR:             return XMC_TERM_CHAR_LITERAL;
    case TT::IDENTIFIER:           return XMC_TERM_IDENTIFIER;
    case TT::UGLY_MASK:            return XMC_TERM_UGLY_MASK;
    // Primitive types
    case TT::KW_B:                 return XMC_TERM_Q_b;
    case TT::KW_I8:                return XMC_TERM_Q_i8;
    case TT::KW_I16:               return XMC_TERM_Q_i16;
    case TT::KW_I32:               return XMC_TERM_Q_i32;
    case TT::KW_I64:               return XMC_TERM_Q_i64;
    case TT::KW_U8:                return XMC_TERM_Q_u8;
    case TT::KW_U16:               return XMC_TERM_Q_u16;
    case TT::KW_U32:               return XMC_TERM_Q_u32;
    case TT::KW_U64:               return XMC_TERM_Q_u64;
    case TT::KW_F32:               return XMC_TERM_Q_f32;
    case TT::KW_F64:               return XMC_TERM_Q_f64;
    case TT::KW_D16:               return XMC_TERM_Q_d16;
    case TT::KW_D32:               return XMC_TERM_Q_d32;
    case TT::KW_D64:               return XMC_TERM_Q_d64;
    case TT::KW_C8:                return XMC_TERM_Q_c8;
    case TT::KW_C16:               return XMC_TERM_Q_c16;
    case TT::KW_ZS8:               return XMC_TERM_Q_zs8;
    case TT::KW_ZS16:              return XMC_TERM_Q_zs16;
    case TT::KW_ZS32:              return XMC_TERM_Q_zs32;
    case TT::KW_S8:                return XMC_TERM_Q_s8;
    case TT::KW_S16:               return XMC_TERM_Q_s16;
    case TT::KW_UTF8:              return XMC_TERM_Q_utf8;
    case TT::KW_US:                return XMC_TERM_Q_us;
    // Container types
    case TT::KW_LIST:              return XMC_TERM_Q_list;
    case TT::KW_QUEUE:             return XMC_TERM_Q_queue;
    case TT::KW_STACK:             return XMC_TERM_Q_stack;
    case TT::KW_BTREE:             return XMC_TERM_Q_btree;
    case TT::KW_HASHSET:           return XMC_TERM_Q_hashset;
    case TT::KW_HASHMAP:           return XMC_TERM_Q_hashmap;
    case TT::KW_SPSC_QUEUE:        return XMC_TERM_Q_spsc_queue;
    case TT::KW_SPMC_QUEUE:        return XMC_TERM_Q_spmc_queue;
    case TT::KW_MPSC_QUEUE:        return XMC_TERM_Q_mpsc_queue;
    case TT::KW_MPMC_QUEUE:        return XMC_TERM_Q_mpmc_queue;
    // Declaration keywords
    case TT::KW_VAR:               return XMC_TERM_Q_var;
    case TT::KW_LET:               return -1;  // reserved, not in grammar
    case TT::KW_REF:               return XMC_TERM_Q_ref;
    case TT::KW_NAMESPACE:         return XMC_TERM_Q_namespace;
    case TT::KW_STRUCT:            return XMC_TERM_Q_struct;
    case TT::KW_CLASS:             return XMC_TERM_Q_class;
    case TT::KW_ERROR:             return XMC_TERM_Q_error;
    case TT::KW_EXTERN:            return XMC_TERM_Q_extern;
    case TT::KW_WEAK:              return -1;  // reserved, not in grammar
    case TT::KW_ARENA:             return XMC_TERM_Q_arena;
    case TT::KW_HEAP:              return XMC_TERM_Q_heap;
    case TT::KW_FUNCTION:          return XMC_TERM_Q_function;
    // Value / builtin keywords
    case TT::KW_NULL:              return XMC_TERM_Q_null;
    case TT::KW_ME:                return XMC_TERM_Q_me;
    case TT::KW_IS:                return XMC_TERM_Q_is;
    case TT::KW_TRUE:              return -1;  // BOOL-LITERAL not in grammar
    case TT::KW_FALSE:             return -1;
    case TT::KW_MISSING_ATTRIBUTE: return XMC_TERM_Q___missing_attribute;
    case TT::KW_RANGE:             return XMC_TERM_Q_range;
    // Control flow
    case TT::KW_IF:                return XMC_TERM_Q_if;
    case TT::KW_THEN:              return XMC_TERM_Q_then;
    case TT::KW_ELSE:              return XMC_TERM_Q_else;
    case TT::KW_FOR:               return XMC_TERM_Q_for;
    case TT::KW_WHILE:             return XMC_TERM_Q_while;
    case TT::KW_DO:                return XMC_TERM_Q_do;
    case TT::KW_IN:                return XMC_TERM_Q_in;
    case TT::KW_RETURN:            return XMC_TERM_Q_return;
    case TT::KW_YIELD:             return XMC_TERM_Q_yield;
    case TT::KW_BREAK:             return XMC_TERM_Q_break;
    case TT::KW_SPAWN:             return XMC_TERM_Q_spawn;
    // Low-refinement qualifiers
    case TT::KW_IMMUTABLE:         return XMC_TERM_Q_immutable;
    case TT::KW_FIXED:             return XMC_TERM_Q_fixed;
    case TT::KW_MATERIALIZED:      return XMC_TERM_Q_materialized;
    case TT::KW_RAW:               return XMC_TERM_Q_raw;
    case TT::KW_HOMOGENOUS:        return XMC_TERM_Q_homogenous;
    case TT::KW_RIGID:             return XMC_TERM_Q_rigid;
    case TT::KW_SERIAL:            return XMC_TERM_Q_serial;
    case TT::KW_SINGULAR:          return XMC_TERM_Q_singular;
    // High-refinement qualifiers (trailing space in BNF spelling → trailing _ in cname)
    case TT::KW_MUTABLE:           return XMC_TERM_Q_mutable_;
    case TT::KW_RESIZABLE:         return XMC_TERM_Q_resizable_;
    case TT::KW_VIRTUAL:           return XMC_TERM_Q_virtual_;
    case TT::KW_ARC:               return XMC_TERM_Q_arc;   // "arc " handled in ContextualAction
    case TT::KW_HETEROGENOUS:      return XMC_TERM_Q_heterogenous_;
    case TT::KW_FLUID:             return XMC_TERM_Q_fluid_;
    case TT::KW_CONCURRENT:        return XMC_TERM_Q_concurrent_;
    case TT::KW_VARIANT:           return XMC_TERM_Q_variant_;
    // Operators
    case TT::OP_ASSIGN:            return XMC_TERM_Q_EQ;
    case TT::OP_ASSIGN_REF:        return XMC_TERM_Q_COLEQ;
    case TT::OP_PLUS:              return XMC_TERM_Q_PLUS;
    case TT::OP_MINUS:             return XMC_TERM_Q_MINUS;
    case TT::OP_STAR:              return XMC_TERM_Q_STAR;
    case TT::OP_SLASH:             return XMC_TERM_Q_SLASH;
    case TT::OP_PERCENT:           return XMC_TERM_Q_PCT;
    case TT::OP_PLUS_ASSIGN:       return XMC_TERM_Q_PLUSEQ;
    case TT::OP_MINUS_ASSIGN:      return XMC_TERM_Q_MINUSEQ;
    case TT::OP_STAR_ASSIGN:       return XMC_TERM_Q_STAREQ;
    case TT::OP_SLASH_ASSIGN:      return XMC_TERM_Q_SLASHEQ;
    case TT::OP_PERCENT_ASSIGN:    return XMC_TERM_Q_PCTEQ;
    case TT::OP_AMP_ASSIGN:        return XMC_TERM_Q_AMPEQ;
    case TT::OP_PIPE_ASSIGN:       return XMC_TERM_Q_PIPEEQ;
    case TT::OP_CARET_ASSIGN:      return XMC_TERM_Q_XOREQ;
    case TT::OP_LSHIFT_ASSIGN:     return -1;  // not in grammar
    case TT::OP_RSHIFT_ASSIGN:     return -1;
    case TT::OP_EQ:                return XMC_TERM_Q_EQEQ;
    case TT::OP_NEQ:               return XMC_TERM_Q_BANGEQ;
    case TT::OP_LT:                return XMC_TERM_Q_LT;
    case TT::OP_GT:                return XMC_TERM_Q_GT;
    case TT::OP_LTE:               return XMC_TERM_Q_LTEQ;
    case TT::OP_GTE:               return XMC_TERM_Q_GTEQ;
    case TT::OP_LSHIFT:            return XMC_TERM_Q_LTLT;
    case TT::OP_RSHIFT:            return XMC_TERM_Q_GTGT;
    case TT::OP_AMP:               return XMC_TERM_Q_AMP;
    case TT::OP_PIPE:              return XMC_TERM_Q_PIPE;
    case TT::OP_CARET:             return XMC_TERM_Q_XOR;
    case TT::OP_TILDE:             return XMC_TERM_Q_TILD;
    case TT::OP_AND:               return XMC_TERM_Q_AMPAMP;
    case TT::OP_OR:                return XMC_TERM_Q_PIPEPIPE;
    case TT::OP_BANG:              return XMC_TERM_Q_BANG;
    case TT::OP_PLUSPLUS:          return XMC_TERM_Q_PLUSPLUS;
    case TT::OP_MINUSMINUS:        return XMC_TERM_Q_MINUSMINUS;
    case TT::OP_AT:                return XMC_TERM_Q_AT;
    case TT::OP_DOLLAR:            return XMC_TERM_Q_DOLLAR;
    case TT::OP_ARROW:             return XMC_TERM_Q_MINUSGT;
    // Punctuation
    case TT::PUNCT_DOT:            return XMC_TERM_Q_DOT;
    case TT::PUNCT_COMMA:          return XMC_TERM_Q_COM;
    case TT::PUNCT_SEMICOLON:      return XMC_TERM_Q_SEMI;
    case TT::PUNCT_COLON:          return XMC_TERM_Q_COL;
    case TT::PUNCT_LPAREN:         return XMC_TERM_Q_LP;
    case TT::PUNCT_RPAREN:         return XMC_TERM_Q_RP;
    case TT::PUNCT_LBRACKET:       return XMC_TERM_Q_LB;
    case TT::PUNCT_RBRACKET:       return XMC_TERM_Q_RB;
    case TT::PUNCT_LBRACE:         return XMC_TERM_Q_LC;
    case TT::PUNCT_RBRACE:         return XMC_TERM_Q_RC;
    case TT::PUNCT_ERROR_OPEN:     return XMC_TERM_Q_LCQM;
    case TT::PUNCT_ERROR_CLOSE:    return XMC_TERM_Q_QMRC;
    // Trivia / diagnostics: filtered before reaching the parser
    case TT::TRIVIA_LINE_COMMENT:
    case TT::TRIVIA_BLOCK_COMMENT:
    case TT::TOK_ERROR:            return -1;
    case TT::TOK_EOF:              return XMC_TERM_EOF;
    default:                       return -1;
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// Table lookup helpers (binary search on sparse rows)
// ─────────────────────────────────────────────────────────────────────────────

static int32_t LookupAction(int state, int term) {
    int lo = XMC_ACT_ROW[state], hi = XMC_ACT_ROW[state + 1] - 1;
    while (lo <= hi) {
        int mid = (lo + hi) / 2;
        if (XMC_ACT[mid].term == term) return XMC_ACT[mid].val;
        if (XMC_ACT[mid].term < term)  lo = mid + 1;
        else                            hi = mid - 1;
    }
    return 0;
}

static int LookupGoto(int state, int nt) {
    int lo = XMC_GOTO_ROW[state], hi = XMC_GOTO_ROW[state + 1] - 1;
    while (lo <= hi) {
        int mid = (lo + hi) / 2;
        if (XMC_GOTO[mid].nt == nt) return XMC_GOTO[mid].state;
        if (XMC_GOTO[mid].nt < nt)  lo = mid + 1;
        else                         hi = mid - 1;
    }
    return -1;
}

// ─────────────────────────────────────────────────────────────────────────────
// Semantic actions
// ─────────────────────────────────────────────────────────────────────────────

static ParseTreeNode* AllocNode(ParseKind k, const Lexer::Token& tk, Xmo& xmo) {
    auto* n = xmo.arena.Construct<ParseTreeNode>();
    n->kind     = k;
    n->srcStart = tk.srcStart;
    n->srcLen   = tk.srcLen;
    n->line     = tk.line;
    n->col      = tk.col;
    return n;
}

static void SetChildren(ParseTreeNode* parent,
                        const std::vector<ParseTreeNode*>& ch,
                        Xmo& xmo) {
    std::vector<ParseTreeNode*> real;
    for (auto* c : ch)
        if (c) real.push_back(c);
    if (real.empty()) return;
    parent->children   = xmo.arena.NewArray<ParseTreeNode*>(static_cast<uint32_t>(real.size()));
    parent->childCount = static_cast<uint32_t>(real.size());
    for (uint32_t i = 0; i < real.size(); i++) {
        parent->children[i] = real[i];
        real[i]->parent = parent;
    }
}

static ParseTreeNode* First(const std::vector<ParseTreeNode*>& ch) {
    for (auto* c : ch)
        if (c) return c;
    return nullptr;
}

static ParseTreeNode* BuildNode(int ri,
                                const std::vector<ParseTreeNode*>& ch,
                                Xmo& xmo,
                                PipelineQueue<ParseTreeNode*>& nodeQueue)
{
    const XmcRule& r  = XMC_RULES[ri];
    const int      nt = r.lhs;

    auto Emit = [&](ParseTreeNode* p) { nodeQueue.Enqueue(std::move(p)); };

    // ── Anonymous nonterminals ($rep_N, $opt_N, $grp_N) ──────────────────
    // All anonymous NTs start with '$' in XMC_NT_STR.
    if (XMC_NT_STR[nt][0] == '$') {
        if (r.rhs_len == 0) return nullptr;

        // $rep_N: accumulate children onto a list node.
        const char* t = XMC_NT_STR[nt] + 1;
        if (t[0] == 'r' && t[1] == 'e' && t[2] == 'p') {
            auto* acc = ch[0];
            std::vector<ParseTreeNode*> items;
            if (acc)
                for (uint32_t i = 0; i < acc->childCount; i++)
                    items.push_back(acc->children[i]);
            for (size_t i = 1; i < ch.size(); i++)
                if (ch[i]) items.push_back(ch[i]);
            if (items.empty()) return nullptr;
            if (!acc) { Lexer::Token dummy{}; acc = AllocNode(ParseKind::Unknown, dummy, xmo); }
            acc->children   = xmo.arena.NewArray<ParseTreeNode*>(static_cast<uint32_t>(items.size()));
            acc->childCount = static_cast<uint32_t>(items.size());
            for (uint32_t i = 0; i < items.size(); i++) {
                acc->children[i] = items[i];
                if (items[i]) items[i]->parent = acc;
            }
            return acc;
        }

        return First(ch);  // $opt_N / $grp_N: transparent pass-through
    }

    // ── Named nonterminals ─────────────────────────────────────────────────
    Lexer::Token loc{};
    for (auto* c : ch)
        if (c) { loc.srcStart=c->srcStart; loc.srcLen=c->srcLen; loc.line=c->line; loc.col=c->col; break; }

    // Transparent pass-throughs (pure integer comparisons)
    if (nt == XMC_NT_top_level_declaration   ||
        nt == XMC_NT_statement               ||
        nt == XMC_NT_expression              ||
        nt == XMC_NT_logical_or_expr         ||
        nt == XMC_NT_logical_and_expr        ||
        nt == XMC_NT_bitwise_or_expr         ||
        nt == XMC_NT_bitwise_xor_expr        ||
        nt == XMC_NT_bitwise_and_expr        ||
        nt == XMC_NT_equality_expr           ||
        nt == XMC_NT_relational_expr         ||
        nt == XMC_NT_shift_expr              ||
        nt == XMC_NT_additive_expr           ||
        nt == XMC_NT_multiplicative_expr     ||
        nt == XMC_NT_unary_expr              ||
        nt == XMC_NT_postfix_expr            ||
        nt == XMC_NT_primary_expr            ||
        nt == XMC_NT_lvalue_expression       ||
        nt == XMC_NT_lvalue_root)
        return First(ch);

	switch (nt)
	{
	case XMC_NT_program:
		{
			auto* n = AllocNode(ParseKind::File, loc, xmo);
			auto* rep = ch[0];
			if (rep) {
				n->children = rep->children;
				n->childCount = rep->childCount;
				for (uint32_t i = 0; i < n->childCount; i++)
					if (n->children[i]) n->children[i]->parent = n;
			}
			Emit(n);
			return n;
		}
	case XMC_NT_extern_declaration:
		{
			auto* n = AllocNode(ParseKind::ExternDecl, loc, xmo);
			auto* qname = ch.size() > 1 ? ch[1] : nullptr;
			if (qname) { n->qualifier = qname->qualifier; n->name = qname->name; }
			SetChildren(n, { ch.size() > 3 ? ch[3] : nullptr,
							 ch.size() > 5 ? ch[5] : nullptr }, xmo);
			Emit(n);
			return n;
		}
	case XMC_NT_function_declaration:
		{
			auto* n = AllocNode(ParseKind::FuncDecl, loc, xmo);
			std::vector<ParseTreeNode*> subs;
			for (auto* c : ch)
				if (c && c->kind != ParseKind::Unknown) subs.push_back(c);
			SetChildren(n, subs, xmo);
			Emit(n);
			return n;
		}
	case XMC_NT_parameter_list:
		{
			auto* n = AllocNode(ParseKind::ParamList, loc, xmo);
			SetChildren(n, ch, xmo);
			Emit(n);
			return n;
		}
	case XMC_NT_parameter:
		{
			auto* n = AllocNode(ParseKind::Param, loc, xmo);
			SetChildren(n, ch, xmo);
			Emit(n);
			return n;
		}
	case XMC_NT_block:
		{
			auto* n = AllocNode(ParseKind::Block, loc, xmo);
			SetChildren(n, ch, xmo);
			Emit(n);
			return n;
		}
	case XMC_NT_expression_statement:
		{
			auto* n = AllocNode(ParseKind::ExprStmt, loc, xmo);
			SetChildren(n, ch, xmo);
			Emit(n);
			return n;
		}
	case XMC_NT_variable_declaration:
		{
			auto* n = AllocNode(ParseKind::VarDecl, loc, xmo);
			SetChildren(n, ch, xmo);
			Emit(n);
			return n;
		}
	case XMC_NT_return_statement:
		{
			auto* n = AllocNode(ParseKind::Return, loc, xmo);
			SetChildren(n, ch, xmo);
			Emit(n);
			return n;
		}
	case XMC_NT_type_specifier:
	case XMC_NT_base_type:
	case XMC_NT_parameter_type_specifier:
		{
			auto* n = AllocNode(ParseKind::Type, loc, xmo);
			auto* inner = First(ch);
			if (inner && inner->kind == ParseKind::Type) return inner;
			SetChildren(n, ch, xmo);
			Emit(n);
			return n;
		}
	case XMC_NT_ptr_type:
		{
			auto* n = AllocNode(ParseKind::Type, loc, xmo);
			SetChildren(n, ch, xmo);
			Emit(n);
			return n;
		}
	case XMC_NT_qualified_name:
		{
			auto* n = First(ch);
			if (!n) return nullptr;
			if (n->kind != ParseKind::Ident) {
				auto* wrap = AllocNode(ParseKind::Ident, loc, xmo);
				wrap->name = n->name;
				n = wrap;
			}
			for (size_t i = 1; i < ch.size(); i++) {
				if (ch[i] && ch[i]->kind == ParseKind::Ident) {
					n->qualifier = n->name;
					n->name = ch[i]->name;
				}
			}
			return n;
		}
	case XMC_NT_function_call:
		{
			auto* n = AllocNode(ParseKind::Call, loc, xmo);
			SetChildren(n, ch, xmo);
			Emit(n);
			return n;
		}
	case XMC_NT_argument_list:
		{
			auto* n = AllocNode(ParseKind::ArgList, loc, xmo);
			SetChildren(n, ch, xmo);
			Emit(n);
			return n;
		}
	}
	
	return First(ch);  // default: transparent for unhandled nonterminals
}

// ─────────────────────────────────────────────────────────────────────────────
// Leaf-node constructors
// ─────────────────────────────────────────────────────────────────────────────

static ParseTreeNode* MakeLeaf(const Lexer::Token& tok,
                               std::string_view src,
                               Xmo& xmo,
                               SymbolTable& symbols,
                               PipelineQueue<ParseTreeNode*>& nodeQueue)
{
    auto make = [&](ParseKind k) -> ParseTreeNode* {
        auto* n = AllocNode(k, tok, xmo);
        ParseTreeNode* p = n;
        nodeQueue.Enqueue(std::move(p));
        return n;
    };

    switch (tok.type) {
    case TT::IDENTIFIER: {
        auto* n = make(ParseKind::Ident);
        n->name = symbols.InternString(tok.Text(src));
        return n;
    }
    case TT::LIT_INTEGER: {
        auto* n = make(ParseKind::IntLit);
        std::string_view t = tok.Text(src);
        if (t.size() >= 2 && t[0]=='0' && (t[1]=='x'||t[1]=='X'))
            n->intValue = std::stoull(std::string(t.substr(2)), nullptr, 16);
        else if (t.size() >= 2 && t[0]=='0' && (t[1]=='b'||t[1]=='B'))
            n->intValue = std::stoull(std::string(t.substr(2)), nullptr, 2);
        else
            n->intValue = std::stoull(std::string(t));
        return n;
    }
    case TT::LIT_FLOAT: {
        auto* n = make(ParseKind::FloatLit);
        n->floatValue = std::stod(std::string(tok.Text(src)));
        return n;
    }
    case TT::LIT_STRING:  return make(ParseKind::StringLit);
    case TT::LIT_CHAR:    return make(ParseKind::CharLit);
    case TT::KW_NULL:     return make(ParseKind::NullLit);
    case TT::KW_TRUE:
    case TT::KW_FALSE:    return make(ParseKind::BoolLit);
    default:
        return AllocNode(ParseKind::Unknown, tok, xmo);
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// Contextual overrides
// ─────────────────────────────────────────────────────────────────────────────

// KW_ARC: "arc" is the primary terminal; "arc " (with trailing space) is the
// high-refinement qualifier spelling used in parameter-type-specifier context.
// If the table has no action for "arc" in the current state, try "arc ".
static int32_t ContextualAction(int state, const Lexer::Token& tok) {
    if (tok.type == TT::KW_ARC)
        return LookupAction(state, XMC_TERM_Q_arc_);
    return 0;
}

// ─────────────────────────────────────────────────────────────────────────────
// LALR(1) main loop
// ─────────────────────────────────────────────────────────────────────────────
// Parser log helpers
// ─────────────────────────────────────────────────────────────────────────────

// Returns up to `len` bytes of source starting at `start`, with newlines/tabs
// collapsed to spaces — used for the "raw text" suffix of literal log entries.
static std::string Excerpt(std::string_view src, uint32_t start, uint32_t len)
{
    if (start >= src.size()) return {};
    uint32_t end = start + len;
    if (end > (uint32_t)src.size()) end = (uint32_t)src.size();
    std::string out;
    out.reserve(end - start);
    for (uint32_t i = start; i < end; ++i) {
        char c = src[i];
        if (c == '\n' || c == '\r' || c == '\t') c = ' ';
        out += c;
    }
    return out;
}

static void DumpNode(std::ofstream& out,
                     const ParseTreeNode* n,
                     std::string_view fileName,
                     std::string_view source,
                     int depth)
{
    if (!n) return;

    // Position prefix padded to column 24 (matches lexer log width).
    std::string pos = std::string(fileName) + ":" +
                      std::to_string(n->line) + ":" + std::to_string(n->col);
    out.write(pos.data(), (std::streamsize)pos.size());
    for (size_t pad = pos.size(); pad < 24; ++pad) out.put(' ');

    // Indent.
    for (int i = 0; i < depth; ++i) out.put(' '), out.put(' ');

    // Kind name.
    out << ParseKindName(n->kind);

    // Per-kind interesting fields.
    switch (n->kind) {
    case ParseKind::ExternDecl:
    case ParseKind::FuncDecl:
    case ParseKind::Param:
    case ParseKind::VarDecl:
    case ParseKind::Ident:
    case ParseKind::MemberAccess:
        out << "  ";
        if (n->qualifier.str && n->qualifier.len)
            out.write(n->qualifier.str, n->qualifier.len), out << ":";
        if (n->name.str && n->name.len)
            out.write(n->name.str, n->name.len);
        if (n->kind == ParseKind::Param && n->regHint.str && n->regHint.len)
            out << " : ", out.write(n->regHint.str, n->regHint.len);
        break;
    case ParseKind::ReturnSpec:
        if (n->regHint.str && n->regHint.len)
            out << "  : ", out.write(n->regHint.str, n->regHint.len);
        break;
    case ParseKind::Type:
        out << "  ";
        for (uint8_t i = 0; i < n->pointerDepth; ++i) out << '*';
        if (n->name.str && n->name.len) out.write(n->name.str, n->name.len);
        if (n->isArray) out << "[]";
        break;
    case ParseKind::IntLit:
        out << "  " << Excerpt(source, n->srcStart, n->srcLen)
            << "  (=" << n->intValue << ")";
        break;
    case ParseKind::FloatLit:
    case ParseKind::StringLit:
    case ParseKind::CharLit:
        out << "  " << Excerpt(source, n->srcStart, n->srcLen);
        break;
    case ParseKind::BoolLit:
        out << "  " << (n->intValue ? "true" : "false");
        break;
    case ParseKind::BinOp:
    case ParseKind::Assign:
    case ParseKind::AddressOf:
    case ParseKind::Deref:
    case ParseKind::Negate:
    case ParseKind::UnaryPlus:
    case ParseKind::Not:
    case ParseKind::BitNot:
        if (n->opToken)
            out << "  " << Lexer::TokenTypeName(Lexer::TokenType(n->opToken));
        break;
    default:
        break;
    }

    out << '\n';

    for (uint32_t i = 0; i < n->childCount; ++i)
        DumpNode(out, n->children[i], fileName, source, depth + 1);
}

// Writes the parser log to <sourceStem>.parser.txt.
// On success pass the completed root; on error pass nullptr and the stack
// fragments will be written as top-level entries so debugging is still useful.
static void WriteParserLog(const ParseTreeNode* root,
                           const std::vector<ParseTreeNode*>& partial,
                           std::string_view fileName,
                           std::string_view source)
{
    fs::path src(fileName);
    fs::path logPath = src.parent_path() / (src.stem().string() + ".parser.txt");
    std::ofstream out(logPath);
    if (!out) return;

    if (root) {
        DumpNode(out, root, fileName, source, 0);
    } else {
        // Error path: dump each partial node that was on the parse stack.
        for (const ParseTreeNode* n : partial)
            DumpNode(out, n, fileName, source, 0);
    }
}

// ─────────────────────────────────────────────────────────────────────────────

struct Frame {
    int            state;
    ParseTreeNode* node;
};

void Parser::Parse(
    Xmo&                           xmo,
    std::string_view               source,
    PipelineQueue<Lexer::Token>&   tokQueue,
    PipelineQueue<ParseTreeNode*>& nodeQueue,
    SymbolTable&                   symbols,
    const CompileJob&              job)
{
    std::vector<Frame> stk;
    stk.reserve(64);
    stk.push_back({0, nullptr});

    Lexer::Token tok{};
    tokQueue.WaitDequeue(tok);
    ParseTreeNode* root = nullptr;
    bool hadError = false;

    while (true) {
        // Lexer filters trivia before enqueuing, but skip any that slip through.
        while (tok.type == TT::TRIVIA_LINE_COMMENT ||
               tok.type == TT::TRIVIA_BLOCK_COMMENT)
            tokQueue.WaitDequeue(tok);

        int ti = TermIdx(tok.type);
        if (ti < 0) {
            std::cerr << xmo.name << ":" << tok.line << ":" << tok.col
                      << ": unexpected token\n";
            hadError = true;
            break;
        }

        int32_t act = LookupAction(stk.back().state, ti);
        if (act == 0)
            act = ContextualAction(stk.back().state, tok);

        if (act == ACCEPT_VAL) {
            root = stk.back().node;
            break;
        }
        else if (act == 0) {
            std::cerr << xmo.name << ":" << tok.line << ":" << tok.col
                      << ": syntax error\n";
            hadError = true;
            break;
        }
        else if (act > 0) {
            auto* leaf = MakeLeaf(tok, source, xmo, symbols, nodeQueue);
            stk.push_back({act - 1, leaf});
            tokQueue.WaitDequeue(tok);
        }
        else {
            int ri  = -act - 1;
            int len = XMC_RULES[ri].rhs_len;

            std::vector<ParseTreeNode*> ch(len);
            for (int i = len - 1; i >= 0; i--) {
                ch[i] = stk.back().node;
                stk.pop_back();
            }

            auto* n = BuildNode(ri, ch, xmo, nodeQueue);

            int nt = XMC_RULES[ri].lhs;
            int ns = LookupGoto(stk.back().state, nt);
            if (ns < 0) {
                std::cerr << "internal: goto error at state "
                          << stk.back().state << " nt " << nt << "\n";
                hadError = true;
                break;
            }
            stk.push_back({ns, n});
        }
    }

    // Drain remaining tokens so the Lexer pipeline doesn't stall.
    while (tok.type != TT::TOK_EOF)
        tokQueue.WaitDequeue(tok);

    if (hadError)
        job.ErrorOccurred = true;
    else if (root)
        xmo.parseTree = root;

    // Write parser log (success or error) when requested.
    if (job.ParserLog) {
        std::vector<ParseTreeNode*> partial;
        if (!root) {
            // Collect non-null nodes from the parse stack for the partial log.
            for (const Frame& f : stk)
                if (f.node) partial.push_back(f.node);
        }
        WriteParserLog(root, partial, xmo.name, source);
    }

    ParseTreeNode* sentinel = nullptr;
    nodeQueue.Enqueue(std::move(sentinel));
}

} // namespace xmc
